apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-01
spec:
  selector:
    matchLabels:
      type: app
  replicas: 2
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        type: app
    spec:
      containers:
        - name: con-01
          image: tmkube/app:v1
      terminationGracePeriodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: svc-1
spec:
  type: LoadBalancer
  selector:
    type: app
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
