apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job-02
spec:
  schedule: "16,17,18 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: con-01
            image: tmkube/init
            command: ["sh", "-c", "echo 'job start'; sleep 140; echo 'job end'"]