apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-01
spec:
  selector:
    matchLabels:
      type: app
  template:
    metadata:
      labels:
        type: app
    spec:
      containers:
        - name: con-01
          image: tmkube/app
          ports:
            - containerPort: 8080
              hostPort: 18080