apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-1  
spec:
  containers:
  - name: container1
    image: kubetm/init
    volumeMounts:
      - mountPath: /mount1
        name: empty-dir        
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"        
  - name: container2
    image: kubetm/init
    volumeMounts:
      - mountPath: /mount2
        name: empty-dir        
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: empty-dir
    emptyDir: {}