apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-3
spec:
  containers:
  - name: pod-volume-5
    image: tmkube/init
    volumeMounts:
      - mountPath: /mount3
        name: pvc-pv
  volumes:
  - name: pvc-pv
    persistentVolumeClaim:
      claimName: pvc-01