apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-1
spec:
  replicas: 2
  selector:
    matchLabels:
      type: web
  template:
    metadata:
      name: pod-1 # 무시
      labels:
        type: web
    spec:
      containers:
      - name: con-1
        image: tmkube/app:v1
      terminationGracePeriodSeconds: 0