apiVersion: v1
kind: Pod
metadata:
  name: pod-liveness-httpget
  labels:
    app: liveness
spec:
  containers:
    - name: con-liveness-httpget
      image: kubetm/app
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
        failureThreshold: 3

        