apiVersion: v1
kind: Pod
metadata:
  name: pod-readiness
  labels:
    app: readiness
spec:
  containers:
    - name: con-01
      image: kubetm/app
      ports:
      - containerPort: 8080
  terminationGracePeriodSeconds: 0