apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  namespace: nm-3
  labels:
    app: pod
spec:
  containers:
    - name: container
      image: tmkube/app
      resources:
        requests:
          memory: 0.2Gi
        limits:
          memory: 0.2Gi
      ports:
      - containerPort: 8080
