apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: pod
spec:
  nodeSelector:
    kubernetes.io/hostname: aks-agentpool-19228959-vmss000000
  containers:
    - name: container
      image: tmkube/app
      ports:
      - containerPort: 8080
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
    
